### ISSUE TITLE
No module named tkinter

### ISSUE THREAD

**Issue by uchuu-me** [delington/DBCommander_Theme_Changer#1]
python3 main.py 
Traceback (most recent call last):
  File "/home/user/dc-theme-changer/main.py", line 5, in <module>
    import service.folder_selector_manager as folder_selector_manager
  File "/home/user/dc-theme-changer/service/folder_selector_manager.py", line 2, in <module>
    from tkinter.filedialog import askdirectory
ModuleNotFoundError: No module named 'tkinter'

**Comment by delington** [comment]
tkinter is the standard GUI library for Python, and it is often included with Python by default on many systems. 
Though I included it in the requirements.txt now, so if you run `pip install -r requirements.txt` it should install tkinter. If not please install it by using `pip install tkinter` .

**Comment by cas--** [comment]
For reference there is no PyPI package for tkinter so `pip install tkinter` will not work: https://stackoverflow.com/questions/76105218/why-does-tkinter-or-turtle-seem-to-be-missing-or-broken-shouldnt-it-be-part

On Debian/Ubuntu this can be resolved with `apt install python3-tk`
